### ISSUE TITLE
Mission (flight) button

### ISSUE THREAD

**Issue by jinamshah** [precision-sustainable-ag/drone-image-manipulation#24]
Implement collapsible button for displaying mission information
Main information (present on button) - mission date, rgb/multispectral imagery
Other information - seen when button is expanded (will have a space to display longform text - comments)

- [x] depends on: https://github.com/precision-sustainable-ag/drone-image_processing-api/issues/14
- [ ] update prod db with updated cloudiness buckets for processed data

Metadata list:
**Primary**: 'mission_start_time' (just date), 'file_type' (jpeg - rgb, tiff - multispectral)
**Collapsible**:
'research_station', 'cloudiness' (can expect buckets of 0-20, 20-40, etc)
'camera_make', 'camera_model'
'pilot_name'
'comments'

**Assets**
camera icon:
(https://github.com/user-attachments/assets/59cc1f58-045f-40b6-a471-d30ced1d6d7d)
(https://github.com/user-attachments/assets/02c4c343-0a8f-4e98-997f-ed0d51dd8470

**Comment by akshat22** [comment]
@jinamshah if this is done you can close this issue

> update prod db with updated cloudiness buckets for processed data
